# Render.com frontend deployment configuration

# Build Command: npm install && npm run build
# Publish Directory: dist

# Environment Variables to set in Render:
# VITE_API_URL=https://your-backend-app.onrender.com/api
# VITE_SOCKET_URL=https://your-backend-app.onrender.com
# VITE_APP_NAME=FoodExpress
# VITE_APP_VERSION=1.0.0
# VITE_NODE_ENV=production
# VITE_FIREBASE_API_KEY=your_firebase_api_key
# VITE_FIREBASE_AUTH_DOMAIN=your_project.firebaseapp.com
# VITE_FIREBASE_PROJECT_ID=your_project_id
# VITE_FIREBASE_STORAGE_BUCKET=your_project.appspot.com
# VITE_FIREBASE_MESSAGING_SENDER_ID=your_sender_id
# VITE_FIREBASE_APP_ID=your_app_id

# Note: Make sure to update the API URLs after backend is deployed
